CREATE TABLE "earthquake" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "geo_id" bigint NOT NULL,
  "report_id" bigint NOT NULL,
  "feature_id" varchar(255) NOT NULL,
  "mag" decimal NOT NULL,
  "time" timestamp NOT NULL,
  "updated_time" timestamp,
  "tz" integer,
  "url" varchar(255) NOT NULL,
  "detail" text NOT NULL,
  "status" text NOT NULL,
  "tsunami" integer NOT NULL,
  "sig" integer NOT NULL,
  "net" text NOT NULL,
  "code" varchar(250) NOT NULL,
  "nst" integer,
  "dmin" decimal,
  "rms" decimal NOT NULL,
  "gap" decimal,
  "magType" text NOT NULL,
  "eq_type" varchar(50) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "geometry" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_id" bigint,
  "longitude" decimal NOT NULL,
  "latitude" decimal NOT NULL,
  "depth" decimal NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "location" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place" text NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "source" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "eq_id" bigint NOT NULL,
  "name" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "report" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "felt" integer,
  "cdi" decimal,
  "mmi" decimal,
  "alert" text,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "feature_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "eq_id" bigint NOT NULL,
  "feat_type" varchar(255) NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "apireq" (
  "id" bigint PRIMARY KEY,
  "req_time" timestamp NOT NULL,
  "req_param" JSON NOT NULL,
  "req_body" JSON,
  "req_headers" JSON,
  "req_metadata" JSONB,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp 
);

ALTER TABLE "earthquake" ADD FOREIGN KEY ("geo_id") REFERENCES "geometry" ("id");

ALTER TABLE "earthquake" ADD FOREIGN KEY ("report_id") REFERENCES "report" ("id");

ALTER TABLE "geometry" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "source" ADD FOREIGN KEY ("eq_id") REFERENCES "earthquake" ("id");

ALTER TABLE "feature_type" ADD FOREIGN KEY ("eq_id") REFERENCES "earthquake" ("id");