CREATE TABLE "earthquake" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "geo_id" bigint NOT NULL,
  "report_id" bigint NOT NULL,
  "mag" decimal NOT NULL,
  "time" timestamp NOT NULL,
  "updated_time" timestamp,
  "tz" integer,
  "url" varchar(255),
  "detail" text,
  "status" text,
  "tsunami" integer,
  "sig" integer,
  "net" text,
  "code" varchar(250),
  "nst" integer,
  "dmin" decimal,
  "rms" decimal,
  "gap" decimal,
  "mag_type" text,
  "eq_type" varchar(50),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "geometry" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "location_id" bigint,
  "longitude" decimal NOT NULL,
  "latitude" decimal NOT NULL,
  "depth" decimal NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "location" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "place" text,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "report" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "felt" integer,
  "cdi" decimal,
  "mmi" decimal,
  "alert" text,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "source" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "source_earthquake" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "s_id" bigint NOT NULL,
  "eq_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "feature_type" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "feat_type" varchar(255),
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "ftype_earthquake" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "ft_id" bigint NOT NULL,
  "eq_id" bigint NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

CREATE TABLE "apireq" (
  "id" bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "req_time" timestamp NOT NULL,
  "req_param" text,
  "req_body" text,
  "req_headers" text,
  "req_metadata" JSONB,
  "resp_time" timestamp NOT NULL, 
  "resp_status" int,
  "resp_headers" text,
  "resp_body" text,
  "resp_metadata" JSONB,
  "created_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "updated_at" timestamp NOT NULL DEFAULT (CURRENT_TIMESTAMP),
  "deleted_at" timestamp
);

ALTER TABLE "earthquake" ADD FOREIGN KEY ("geo_id") REFERENCES "geometry" ("id");

ALTER TABLE "earthquake" ADD FOREIGN KEY ("report_id") REFERENCES "report" ("id");

ALTER TABLE "geometry" ADD FOREIGN KEY ("location_id") REFERENCES "location" ("id");

ALTER TABLE "source_earthquake" ADD FOREIGN KEY ("s_id") REFERENCES "source" ("id");

ALTER TABLE "source_earthquake" ADD FOREIGN KEY ("eq_id") REFERENCES "earthquake" ("id");

ALTER TABLE "ftype_earthquake" ADD FOREIGN KEY ("ft_id") REFERENCES "feature_type" ("id");

ALTER TABLE "ftype_earthquake" ADD FOREIGN KEY ("eq_id") REFERENCES "earthquake" ("id");