// Code generated by ent, DO NOT EDIT.

package schemamigration

import (
	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the schemamigration type in the database.
	Label = "schema_migration"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "version"
	// FieldDirty holds the string denoting the dirty field in the database.
	FieldDirty = "dirty"
	// Table holds the table name of the schemamigration in the database.
	Table = "schema_migrations"
)

// Columns holds all SQL columns for schemamigration fields.
var Columns = []string{
	FieldID,
	FieldDirty,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

// OrderOption defines the ordering options for the SchemaMigration queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByDirty orders the results by the dirty field.
func ByDirty(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDirty, opts...).ToFunc()
}
