// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"golang-intern/assignment-2/ent/predicate"
	"golang-intern/assignment-2/ent/schemamigration"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// SchemaMigrationQuery is the builder for querying SchemaMigration entities.
type SchemaMigrationQuery struct {
	config
	ctx        *QueryContext
	order      []schemamigration.OrderOption
	inters     []Interceptor
	predicates []predicate.SchemaMigration
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the SchemaMigrationQuery builder.
func (smq *SchemaMigrationQuery) Where(ps ...predicate.SchemaMigration) *SchemaMigrationQuery {
	smq.predicates = append(smq.predicates, ps...)
	return smq
}

// Limit the number of records to be returned by this query.
func (smq *SchemaMigrationQuery) Limit(limit int) *SchemaMigrationQuery {
	smq.ctx.Limit = &limit
	return smq
}

// Offset to start from.
func (smq *SchemaMigrationQuery) Offset(offset int) *SchemaMigrationQuery {
	smq.ctx.Offset = &offset
	return smq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (smq *SchemaMigrationQuery) Unique(unique bool) *SchemaMigrationQuery {
	smq.ctx.Unique = &unique
	return smq
}

// Order specifies how the records should be ordered.
func (smq *SchemaMigrationQuery) Order(o ...schemamigration.OrderOption) *SchemaMigrationQuery {
	smq.order = append(smq.order, o...)
	return smq
}

// First returns the first SchemaMigration entity from the query.
// Returns a *NotFoundError when no SchemaMigration was found.
func (smq *SchemaMigrationQuery) First(ctx context.Context) (*SchemaMigration, error) {
	nodes, err := smq.Limit(1).All(setContextOp(ctx, smq.ctx, "First"))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{schemamigration.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (smq *SchemaMigrationQuery) FirstX(ctx context.Context) *SchemaMigration {
	node, err := smq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first SchemaMigration ID from the query.
// Returns a *NotFoundError when no SchemaMigration ID was found.
func (smq *SchemaMigrationQuery) FirstID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(1).IDs(setContextOp(ctx, smq.ctx, "FirstID")); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{schemamigration.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (smq *SchemaMigrationQuery) FirstIDX(ctx context.Context) int {
	id, err := smq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single SchemaMigration entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one SchemaMigration entity is found.
// Returns a *NotFoundError when no SchemaMigration entities are found.
func (smq *SchemaMigrationQuery) Only(ctx context.Context) (*SchemaMigration, error) {
	nodes, err := smq.Limit(2).All(setContextOp(ctx, smq.ctx, "Only"))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{schemamigration.Label}
	default:
		return nil, &NotSingularError{schemamigration.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (smq *SchemaMigrationQuery) OnlyX(ctx context.Context) *SchemaMigration {
	node, err := smq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only SchemaMigration ID in the query.
// Returns a *NotSingularError when more than one SchemaMigration ID is found.
// Returns a *NotFoundError when no entities are found.
func (smq *SchemaMigrationQuery) OnlyID(ctx context.Context) (id int, err error) {
	var ids []int
	if ids, err = smq.Limit(2).IDs(setContextOp(ctx, smq.ctx, "OnlyID")); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{schemamigration.Label}
	default:
		err = &NotSingularError{schemamigration.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (smq *SchemaMigrationQuery) OnlyIDX(ctx context.Context) int {
	id, err := smq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of SchemaMigrations.
func (smq *SchemaMigrationQuery) All(ctx context.Context) ([]*SchemaMigration, error) {
	ctx = setContextOp(ctx, smq.ctx, "All")
	if err := smq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*SchemaMigration, *SchemaMigrationQuery]()
	return withInterceptors[[]*SchemaMigration](ctx, smq, qr, smq.inters)
}

// AllX is like All, but panics if an error occurs.
func (smq *SchemaMigrationQuery) AllX(ctx context.Context) []*SchemaMigration {
	nodes, err := smq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of SchemaMigration IDs.
func (smq *SchemaMigrationQuery) IDs(ctx context.Context) (ids []int, err error) {
	if smq.ctx.Unique == nil && smq.path != nil {
		smq.Unique(true)
	}
	ctx = setContextOp(ctx, smq.ctx, "IDs")
	if err = smq.Select(schemamigration.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (smq *SchemaMigrationQuery) IDsX(ctx context.Context) []int {
	ids, err := smq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (smq *SchemaMigrationQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, smq.ctx, "Count")
	if err := smq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, smq, querierCount[*SchemaMigrationQuery](), smq.inters)
}

// CountX is like Count, but panics if an error occurs.
func (smq *SchemaMigrationQuery) CountX(ctx context.Context) int {
	count, err := smq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (smq *SchemaMigrationQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, smq.ctx, "Exist")
	switch _, err := smq.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (smq *SchemaMigrationQuery) ExistX(ctx context.Context) bool {
	exist, err := smq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the SchemaMigrationQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (smq *SchemaMigrationQuery) Clone() *SchemaMigrationQuery {
	if smq == nil {
		return nil
	}
	return &SchemaMigrationQuery{
		config:     smq.config,
		ctx:        smq.ctx.Clone(),
		order:      append([]schemamigration.OrderOption{}, smq.order...),
		inters:     append([]Interceptor{}, smq.inters...),
		predicates: append([]predicate.SchemaMigration{}, smq.predicates...),
		// clone intermediate query.
		sql:  smq.sql.Clone(),
		path: smq.path,
	}
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Dirty bool `json:"dirty,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.SchemaMigration.Query().
//		GroupBy(schemamigration.FieldDirty).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (smq *SchemaMigrationQuery) GroupBy(field string, fields ...string) *SchemaMigrationGroupBy {
	smq.ctx.Fields = append([]string{field}, fields...)
	grbuild := &SchemaMigrationGroupBy{build: smq}
	grbuild.flds = &smq.ctx.Fields
	grbuild.label = schemamigration.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Dirty bool `json:"dirty,omitempty"`
//	}
//
//	client.SchemaMigration.Query().
//		Select(schemamigration.FieldDirty).
//		Scan(ctx, &v)
func (smq *SchemaMigrationQuery) Select(fields ...string) *SchemaMigrationSelect {
	smq.ctx.Fields = append(smq.ctx.Fields, fields...)
	sbuild := &SchemaMigrationSelect{SchemaMigrationQuery: smq}
	sbuild.label = schemamigration.Label
	sbuild.flds, sbuild.scan = &smq.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a SchemaMigrationSelect configured with the given aggregations.
func (smq *SchemaMigrationQuery) Aggregate(fns ...AggregateFunc) *SchemaMigrationSelect {
	return smq.Select().Aggregate(fns...)
}

func (smq *SchemaMigrationQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range smq.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, smq); err != nil {
				return err
			}
		}
	}
	for _, f := range smq.ctx.Fields {
		if !schemamigration.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if smq.path != nil {
		prev, err := smq.path(ctx)
		if err != nil {
			return err
		}
		smq.sql = prev
	}
	return nil
}

func (smq *SchemaMigrationQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*SchemaMigration, error) {
	var (
		nodes = []*SchemaMigration{}
		_spec = smq.querySpec()
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*SchemaMigration).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &SchemaMigration{config: smq.config}
		nodes = append(nodes, node)
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, smq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	return nodes, nil
}

func (smq *SchemaMigrationQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := smq.querySpec()
	_spec.Node.Columns = smq.ctx.Fields
	if len(smq.ctx.Fields) > 0 {
		_spec.Unique = smq.ctx.Unique != nil && *smq.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, smq.driver, _spec)
}

func (smq *SchemaMigrationQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(schemamigration.Table, schemamigration.Columns, sqlgraph.NewFieldSpec(schemamigration.FieldID, field.TypeInt))
	_spec.From = smq.sql
	if unique := smq.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if smq.path != nil {
		_spec.Unique = true
	}
	if fields := smq.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, schemamigration.FieldID)
		for i := range fields {
			if fields[i] != schemamigration.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := smq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := smq.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := smq.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := smq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (smq *SchemaMigrationQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(smq.driver.Dialect())
	t1 := builder.Table(schemamigration.Table)
	columns := smq.ctx.Fields
	if len(columns) == 0 {
		columns = schemamigration.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if smq.sql != nil {
		selector = smq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if smq.ctx.Unique != nil && *smq.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range smq.predicates {
		p(selector)
	}
	for _, p := range smq.order {
		p(selector)
	}
	if offset := smq.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := smq.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// SchemaMigrationGroupBy is the group-by builder for SchemaMigration entities.
type SchemaMigrationGroupBy struct {
	selector
	build *SchemaMigrationQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (smgb *SchemaMigrationGroupBy) Aggregate(fns ...AggregateFunc) *SchemaMigrationGroupBy {
	smgb.fns = append(smgb.fns, fns...)
	return smgb
}

// Scan applies the selector query and scans the result into the given value.
func (smgb *SchemaMigrationGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, smgb.build.ctx, "GroupBy")
	if err := smgb.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SchemaMigrationQuery, *SchemaMigrationGroupBy](ctx, smgb.build, smgb, smgb.build.inters, v)
}

func (smgb *SchemaMigrationGroupBy) sqlScan(ctx context.Context, root *SchemaMigrationQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(smgb.fns))
	for _, fn := range smgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*smgb.flds)+len(smgb.fns))
		for _, f := range *smgb.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*smgb.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := smgb.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// SchemaMigrationSelect is the builder for selecting fields of SchemaMigration entities.
type SchemaMigrationSelect struct {
	*SchemaMigrationQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (sms *SchemaMigrationSelect) Aggregate(fns ...AggregateFunc) *SchemaMigrationSelect {
	sms.fns = append(sms.fns, fns...)
	return sms
}

// Scan applies the selector query and scans the result into the given value.
func (sms *SchemaMigrationSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, sms.ctx, "Select")
	if err := sms.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*SchemaMigrationQuery, *SchemaMigrationSelect](ctx, sms.SchemaMigrationQuery, sms, sms.inters, v)
}

func (sms *SchemaMigrationSelect) sqlScan(ctx context.Context, root *SchemaMigrationQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(sms.fns))
	for _, fn := range sms.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*sms.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := sms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
