// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// Apireq is the predicate function for apireq builders.
type Apireq func(*sql.Selector)

// Earthquake is the predicate function for earthquake builders.
type Earthquake func(*sql.Selector)

// FeatureType is the predicate function for featuretype builders.
type FeatureType func(*sql.Selector)

// FtypeEarthquake is the predicate function for ftypeearthquake builders.
type FtypeEarthquake func(*sql.Selector)

// Geometry is the predicate function for geometry builders.
type Geometry func(*sql.Selector)

// Location is the predicate function for location builders.
type Location func(*sql.Selector)

// Report is the predicate function for report builders.
type Report func(*sql.Selector)

// SchemaMigration is the predicate function for schemamigration builders.
type SchemaMigration func(*sql.Selector)

// Source is the predicate function for source builders.
type Source func(*sql.Selector)

// SourceEarthquake is the predicate function for sourceearthquake builders.
type SourceEarthquake func(*sql.Selector)
